#!/usr/bin/env Rscript

library("optparse")
 
option_list = list(
	make_option(c("-i", "--input_file"), type="character", default=NULL, 
              help="Path to input file, containing KO data for the species' pangenome.", metavar="character"),
	make_option(c("-n", "--species_name"), type="character", default=NULL, 
              help="Species name.", metavar="character"),
	make_option(c("-o", "--outdir"), type="character", default=NULL,
              help="Path to directory to write output in.", metavar="character"),
        make_option(c("-K", "--KO_index"), type="character", default=NULL,
              help="Path to the OG_COG index [optional].", metavar="character")
); 
 
opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);


if (is.null(opt$input_file)){
  print_help(opt_parser)
  stop("Please supply the input file containing KO data for species pangenome, generated by analyse.species-pangenome.sh.", call.=FALSE)
}

if (is.null(opt$species_name)){
  print_help(opt_parser)
  stop("Please supply the genome name.", call.=FALSE)
}

if (is.null(opt$outdir)){
  print_help(opt_parser)
  stop("Please supply the output directory.", call.=FALSE)
}

if (is.null(opt$KO_index)){
  opt$KO_index <- "/lustre/scratch118/infgen/team162/bb11/Human_mouse_comparison/HUMAN_MOUSE_HQ_REPS/PANGENOMES/OG_COGS.txt"
}


# load data
KO <- read.delim(file=opt$KO_index, header=FALSE)
data <- read.delim(file=opt$input_file, header=FALSE)

# standardise column names for merging
colnames(data) <- c("OG_COG", "With", "NR", "Total") 
colnames(KO) <- "OG_COG"

# generate fraction data
data$Fraction <- data$With/data$Total
data$perGenome <- data$NR/data$Total

# merge data to the KO index
merged <- merge(KO, data[,c(1,5,6)], all.x=TRUE)
merged$Fraction[is.na(merged$Fraction)] <- 0


# hard-core genome (≥99%)
hardcore <- merged[,c(1,2)]
hardcore$Fraction[hardcore$Fraction < 0.99] <- 0
hardcore$Fraction[hardcore$Fraction >= 0.99] <- 1
colnames(hardcore)[2] <- opt$species_name

# soft-core genome (≥95%)
softcore <- merged[,c(1,2)]
softcore$Fraction[softcore$Fraction < 0.95] <- 0
softcore$Fraction[softcore$Fraction >= 0.95] <- 1
colnames(softcore)[2] <- opt$species_name

# generate summary statistic info
hc_data <- merged[which(merged$Fraction >= 0.99),]
sc_data <- merged[which(merged$Fraction >= 0.95 & merged$Fraction < 0.99),]
shell_data <- merged[which(merged$Fraction >= 0.15 & merged$Fraction < 0.95),]
cloud_data <- merged[which(merged$Fraction < 0.15),]

n <- paste(opt$species_name, "perGenome", sep = "_")
colnames(merged)[c(2,3)] <- c(opt$species_name, n)


# write output files

core_mat <- paste(opt$outdir, "core-genes_p-a.tsv", sep = "/")
softcore_mat <- paste(opt$outdir, "softcore-genes_p-a.tsv", sep = "/")
data_mat <- paste(opt$outdir, "all-genes_cont.tsv", sep = "/")
hc_out <- paste(opt$outdir, "core-genes.tsv", sep = "/")
sc_out <- paste(opt$outdir, "softcore-genes.tsv", sep = "/")
shell_out <- paste(opt$outdir, "shell-genes.tsv", sep = "/")
cloud_out <- paste(opt$outdir, "cloud-genes.tsv", sep = "/")
data_out <- paste(opt$outdir, "all_data.tsv", sep = "/")


write.table(file=core_mat, x=hardcore, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=softcore_mat, x=softcore, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=data_mat, x=merged, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)

write.table(file=hc_out, x=hc_data, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=sc_out, x=sc_data, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=shell_out, x=shell_data, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=cloud_out, x=cloud_data, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=data_out, x=data, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
