#!/usr/bin/env Rscript

library("optparse")
 
option_list = list(
	make_option(c("-A", "--all_ipr_input"), type="character", default=NULL, 
              help="Path to input file, containing all IPR data for the species' pangenome.", metavar="character"),
        make_option(c("-F", "--family_ipr_input"), type="character", default=NULL,
              help="Path to input file, containing family IPR data for the species' pangenome.", metavar="character"),
	make_option(c("-n", "--species_name"), type="character", default=NULL, 
              help="Species name.", metavar="character"),
	make_option(c("-o", "--outdir"), type="character", default=NULL,
              help="Path to directory to write output in.", metavar="character"),
        make_option(c("-D", "--data_dir"), type="character", default=NULL,
              help="Path to the directory conatining the IPR indices [optional].", metavar="character")
); 
 
opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);


if (is.null(opt$all_ipr_input)){
  print_help(opt_parser)
  stop("Please supply the input file containing all IPR data for species pangenome, generated by analyse.species-pangenome_IPS.sh.", call.=FALSE)
}

if (is.null(opt$family_ipr_input)){
  print_help(opt_parser)
  stop("Please supply the input file containing family IPR data for species pangenome, generated by analyse.species-pangenome_IPS.sh.", call.=FALSE)
}


if (is.null(opt$species_name)){
  print_help(opt_parser)
  stop("Please supply the species name.", call.=FALSE)
}

if (is.null(opt$outdir)){
  print_help(opt_parser)
  stop("Please supply the output directory.", call.=FALSE)
}

if (is.null(opt$data_dir)){
  opt$data_dir <- "/lustre/scratch118/infgen/team162/bb11/External_databases/InterPro"
}

ALL_IPR <- paste(opt$data_dir, "IPS_entries.txt", sep = "/")
FAMILY_IPR <- paste(opt$data_dir, "FAMILY_index.txt", sep = "/")


print("load data")
all_ipr <- read.delim(file=ALL_IPR, header=FALSE)
family_ipr <- read.delim(file=FAMILY_IPR, header=FALSE) 

all_data <- read.delim(file=opt$all_ipr_input, header=FALSE)
family_data <- read.delim(file=opt$family_ipr_input, header=FALSE)

print("standardise column names for merging")
colnames(all_data) <- c("IPR", "With", "Total")
colnames(family_data) <- c("IPR", "With", "NR", "Total") 
colnames(all_ipr) <- "IPR"
colnames(family_ipr) <- "IPR"


### ALL DATA ###

print("generate fraction data")
all_data$Fraction <- all_data$With/all_data$Total

print("merge data to the IPR index")
merged <- merge(all_ipr, all_data[,c(1,4)], all.x=TRUE)
merged$Fraction[is.na(merged$Fraction)] <- 0


print("hard-core genome (≥99%)")
hardcore <- merged
hardcore$Fraction[hardcore$Fraction < 0.99] <- 0
hardcore$Fraction[hardcore$Fraction >= 0.99] <- 1
colnames(hardcore)[2] <- opt$species_name

print("soft-core genome (≥95%)")
softcore <- merged
softcore$Fraction[softcore$Fraction < 0.95] <- 0
softcore$Fraction[softcore$Fraction >= 0.95] <- 1
colnames(softcore)[2] <- opt$species_name

print("generate summary statistic info")
hc_data <- merged[which(merged$Fraction >= 0.99),]
sc_data <- merged[which(merged$Fraction >= 0.95 & merged$Fraction < 0.99),]
shell_data <- merged[which(merged$Fraction >= 0.15 & merged$Fraction < 0.95),]
cloud_data <- merged[which(merged$Fraction < 0.15),]

colnames(merged)[2] <- c(opt$species_name)


print("write output files")

core_mat <- paste(opt$outdir, "ALL_core-genes_p-a.tsv", sep = "/")
softcore_mat <- paste(opt$outdir, "ALL_softcore-genes_p-a.tsv", sep = "/")
data_mat <- paste(opt$outdir, "ALL_all-genes_cont.tsv", sep = "/")
hc_out <- paste(opt$outdir, "ALL_core-genes.tsv", sep = "/")
sc_out <- paste(opt$outdir, "ALL_softcore-genes.tsv", sep = "/")
shell_out <- paste(opt$outdir, "ALL_shell-genes.tsv", sep = "/")
cloud_out <- paste(opt$outdir, "ALL_cloud-genes.tsv", sep = "/")
data_out <- paste(opt$outdir, "ALL_all_data.tsv", sep = "/")


write.table(file=core_mat, x=hardcore, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=softcore_mat, x=softcore, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=data_mat, x=merged, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)

write.table(file=hc_out, x=hc_data, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=sc_out, x=sc_data, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=shell_out, x=shell_data, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=cloud_out, x=cloud_data, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=data_out, x=all_data, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)


print("Analysing family data.")

### FAMILY DATA ###
family_data$Fraction <- family_data$With/family_data$Total
family_data$perGenome <- family_data$NR/family_data$Total

print("merge data to the IPR index")
merged <- merge(family_ipr, family_data[,c(1,5,6)], all.x=TRUE)
merged$Fraction[is.na(merged$Fraction)] <- 0
merged$perGenome[is.na(merged$perGenome)] <- 0

print("hard-core genome (≥99%)")
hardcore <- merged[,c(1,2)]
hardcore$Fraction[hardcore$Fraction < 0.99] <- 0
hardcore$Fraction[hardcore$Fraction >= 0.99] <- 1
colnames(hardcore)[2] <- opt$species_name

print("soft-core genome (≥95%)")
softcore <- merged[,c(1,2)]
softcore$Fraction[softcore$Fraction < 0.95] <- 0
softcore$Fraction[softcore$Fraction >= 0.95] <- 1
colnames(softcore)[2] <- opt$species_name

print("generate summary statistic info")
hc_data <- merged[which(merged$Fraction >= 0.99),]
sc_data <- merged[which(merged$Fraction >= 0.95 & merged$Fraction < 0.99),]
shell_data <- merged[which(merged$Fraction >= 0.15 & merged$Fraction < 0.95),]
cloud_data <- merged[which(merged$Fraction < 0.15),]

n <- paste(opt$species_name, "perGenome", sep = "_")
colnames(merged)[c(2,3)] <- c(opt$species_name, n)

print("write output files")

core_mat <- paste(opt$outdir, "FAM_core-genes_p-a.tsv", sep = "/")
softcore_mat <- paste(opt$outdir, "FAM_softcore-genes_p-a.tsv", sep = "/")
data_mat <- paste(opt$outdir, "FAM_all-genes_cont.tsv", sep = "/")
hc_out <- paste(opt$outdir, "FAM_core-genes.tsv", sep = "/")
sc_out <- paste(opt$outdir, "FAM_softcore-genes.tsv", sep = "/")
shell_out <- paste(opt$outdir, "FAM_shell-genes.tsv", sep = "/")
cloud_out <- paste(opt$outdir, "FAM_cloud-genes.tsv", sep = "/")
data_out <- paste(opt$outdir, "FAM_all_data.tsv", sep = "/")


write.table(file=core_mat, x=hardcore, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=softcore_mat, x=softcore, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=data_mat, x=merged, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)

write.table(file=hc_out, x=hc_data, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=sc_out, x=sc_data, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=shell_out, x=shell_data, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=cloud_out, x=cloud_data, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(file=data_out, x=family_data, sep="\t", col.names=TRUE, row.names=FALSE, quote=FALSE)


